import { getDialect, LATEST_CYODA_VERSION } from "@cyoda/workflow-core";

export interface ToolManifestEntry { name: string; description: string; inputSchema: Record<string, unknown> }

/**
 * The in-document `version` tag new workflows must carry. cyoda-go validates it
 * strictly, so `create_workflow` callers have to get it right — sourced from the
 * dialect rather than hardcoded so a schema bump updates the tool description.
 */
const SCHEMA_VERSION_TAG = getDialect(LATEST_CYODA_VERSION).schemaVersionTag;

const empty = { type: "object", properties: {}, additionalProperties: false } as const;
const nameOnly = { type: "object", properties: { name: { type: "string", minLength: 1 } }, required: ["name"], additionalProperties: false } as const;
const nameAndContent = {
  type: "object",
  properties: { name: { type: "string", minLength: 1 }, content: { type: "string" } },
  required: ["name", "content"],
  additionalProperties: false,
} as const;
const stringArray = { type: "array", items: { type: "string" } } as const;

export const TOOL_MANIFEST: ToolManifestEntry[] = [
  { name: "list_workflows", description: "List discovered workflows: { workflows: [{ name, path, states, transitions, valid, reason? }] }. `reason` (present only when valid:false) is the first error-severity diagnostic — why it's invalid, without a separate validate call.", inputSchema: empty },
  { name: "show_workflow", description: "Render a workflow in the browser and return its parsed document. Canonicalizes on read (operatorType→operation, drops empty context, injects disabled:false); for raw bytes use get_workflow.", inputSchema: nameOnly },
  { name: "get_workflow", description: "Read a single workflow's raw on-disk JSON contents by name — NO canonicalization (unlike show_workflow/update_workflow), so it round-trips byte-faithfully.", inputSchema: nameOnly },
  { name: "create_workflow", description: `Create a new workflow file (name-based; destination dir derived from workflowGlobs). Content is a full import-payload ({importMode, workflows:[...]}), written canonical. New workflows should use the current schema tag \`version: "${SCHEMA_VERSION_TAG}"\`. The tag must be MAJOR.MINOR within the accepted range (malformed, too-new, or retired tags are rejected), and at least the version that introduced any feature the workflow uses (e.g. a \`NOT\` criterion group needs 1.4). Rejects an already-existing name, invalid JSON, or a semantically-invalid document.`, inputSchema: nameAndContent },
  { name: "update_workflow", description: "Validate + whole-document write a workflow; returns a JSON diff. Canonicalizes before writing; for raw bytes use get_workflow.", inputSchema: { type: "object", properties: { name: { type: "string", minLength: 1 }, content: { type: "string" } }, required: ["name", "content"], additionalProperties: false } },
  { name: "delete_workflow", description: "Delete an existing workflow file, and its .layout.json sidecar if present.", inputSchema: nameOnly },
  { name: "update_transition", description: "Patch one transition, addressed by (workflow, state, name). `patch` sets any subset of { name, next, manual, disabled, criterion, processors, schedule, annotations } — provided fields replace (nested values wholesale), omitted preserved. `patch.name` renames but does NOT auto-update lifecycle previousTransition refs (warns instead).", inputSchema: { type: "object", properties: { workflow: { type: "string", minLength: 1 }, state: { type: "string", minLength: 1 }, name: { type: "string", minLength: 1 }, patch: { type: "object", properties: { name: { type: "string", minLength: 1 }, next: { type: "string", minLength: 1 }, manual: { type: "boolean" }, disabled: { type: "boolean" }, criterion: { type: "object" }, processors: { type: "array" }, schedule: { type: "object" }, annotations: { type: "object" } }, additionalProperties: false } }, required: ["workflow", "state", "name", "patch"], additionalProperties: false } },
  { name: "add_transition", description: "Add a new transition to a state. `transition` requires name + next + manual (disabled defaults false). ALREADY_EXISTS if the name is already used in that state; VALIDATION_FAILED if next references a nonexistent state.", inputSchema: { type: "object", properties: { workflow: { type: "string", minLength: 1 }, state: { type: "string", minLength: 1 }, transition: { type: "object", properties: { name: { type: "string", minLength: 1 }, next: { type: "string", minLength: 1 }, manual: { type: "boolean" }, disabled: { type: "boolean" }, criterion: { type: "object" }, processors: { type: "array" }, schedule: { type: "object" }, annotations: { type: "object" } }, required: ["name", "next", "manual"], additionalProperties: false } }, required: ["workflow", "state", "transition"], additionalProperties: false } },
  { name: "remove_transition", description: "Remove a transition, addressed by (workflow, state, name).", inputSchema: { type: "object", properties: { workflow: { type: "string", minLength: 1 }, state: { type: "string", minLength: 1 }, name: { type: "string", minLength: 1 } }, required: ["workflow", "state", "name"], additionalProperties: false } },
  { name: "add_state", description: "Add a new state to a workflow, optionally seeded with transitions (each requires name + next + manual). ALREADY_EXISTS if the code already exists.", inputSchema: { type: "object", properties: { workflow: { type: "string", minLength: 1 }, code: { type: "string", minLength: 1 }, state: { type: "object", properties: { transitions: { type: "array" }, annotations: { type: "object" } }, additionalProperties: false } }, required: ["workflow", "code"], additionalProperties: false } },
  { name: "remove_state", description: "Remove a state. Rejects (VALIDATION_FAILED) if any transition `next`, the `initialState`, or a lifecycle state-criterion still references it — repoint those first. Also removes the state's saved layout position.", inputSchema: { type: "object", properties: { workflow: { type: "string", minLength: 1 }, code: { type: "string", minLength: 1 } }, required: ["workflow", "code"], additionalProperties: false } },
  { name: "rename_state", description: "Rename a state code, cascading every transition `next`, the `initialState`, and lifecycle state-criteria (scalar or array) from oldCode to newCode in one atomic op, and migrating its saved layout position. Does not touch lifecycle `previousTransition` references.", inputSchema: { type: "object", properties: { workflow: { type: "string", minLength: 1 }, oldCode: { type: "string", minLength: 1 }, newCode: { type: "string", minLength: 1 } }, required: ["workflow", "oldCode", "newCode"], additionalProperties: false } },
  { name: "optimize_layout", description: "Re-lay-out a workflow with elkjs; persists node positions to the .layout.json sidecar (live-pushed to the browser). options.orientation: vertical (default) | horizontal. options.preset: websiteCompact | configuratorReadable | opsAudit. options.nodeSize / options.pinned override the per-state box size / fix specific coordinates.", inputSchema: { type: "object", properties: { name: { type: "string", minLength: 1 }, options: { type: "object", properties: { orientation: { enum: ["vertical", "horizontal"] }, preset: { enum: ["websiteCompact", "configuratorReadable", "opsAudit"] }, nodeSize: { type: "object", properties: { width: { type: "number" }, height: { type: "number" } }, required: ["width", "height"], additionalProperties: false }, pinned: { type: "array", items: { type: "object", properties: { id: { type: "string" }, x: { type: "number" }, y: { type: "number" } }, required: ["id", "x", "y"], additionalProperties: false } } }, additionalProperties: false } }, required: ["name"], additionalProperties: false } },
  { name: "validate_workflow", description: "Parse + validate a workflow; returns diagnostics. Read-only.", inputSchema: nameOnly },
  { name: "validate_workflows", description: "Batch validate_workflow: validates every discovered workflow. Read-only. { workflows: [{ name, valid, diagnostics }] }; an unreadable file yields valid:false rather than failing the whole call.", inputSchema: empty },
  { name: "connection_info", description: "Return the live editor's browser URL/port. The port is deterministic per project path but the token regenerates each process start — call again after a restart for the fresh URL.", inputSchema: empty },
  { name: "list_entities", description: "List discovered entities (separate plain-JSON object files matched by entityGlobs): { entities: [{ name, path, lastModified, sizeBytes }] }.", inputSchema: empty },
  { name: "get_entity", description: "Read a single entity's raw JSON contents by name.", inputSchema: nameOnly },
  { name: "show_entity", description: "Render an entity in the browser (switch to its JSON/Tree view) and return its raw JSON. Read-only, no canonicalization — the on-disk bytes as-is.", inputSchema: nameOnly },
  { name: "create_entity", description: "Create a new entity file (name-based; destination directory derived from entityGlobs). Rejects if an entity with that name already exists.", inputSchema: nameAndContent },
  { name: "update_entity", description: "Overwrite an existing entity's whole-document JSON contents.", inputSchema: nameAndContent },
  { name: "delete_entity", description: "Delete an existing entity file.", inputSchema: nameOnly },
  { name: "configure_project", description: "Update the session's workflowGlobs/entityGlobs (and an optional display name) — never persisted to disk.", inputSchema: { type: "object", properties: { name: { type: "string", minLength: 1, maxLength: 200 }, workflowGlobs: stringArray, entityGlobs: stringArray }, additionalProperties: false } },
  { name: "get_project", description: "Report the project root, current workflowGlobs/entityGlobs, and workflow/entity counts; includes the connection URL under _connection.url.", inputSchema: empty },
];
